### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [yuunaK/intro-data-capstone-musclehub#4]
Overall, this was a beautifully done project; great job!

You got all the parts correctly. Great coding style.
The Matplotlib visualizations were gorgeous. Make sure you create the ax object first and then plot, not the other way around. Each visualization communicated your points very well. Did you know you can use different matplotlib styles to make your plots more colorful and stylish. Checkout some examples:
http://nbviewer.jupyter.org/github/qszhuan/qszhuan-notebook/blob/master/data-visualization/Matplotlib%20plotting%20styles.ipynb

Revisit the significant level required for p-values. Generally pvalue is chosen to be 0.05 not 0.5. So results where pvalue is less than <5% are significant while >5% is not. This will change your conclusions.

Your suggestions for further research were also really interesting. Check back on the pvalues significance and think of your conclusion regarding people who took the fitness test were more likely to purchase a membership if they picked up an application.

**Comment by yuunaK** [comment]
Thank you Abhisek for you kind comments.

Thank you very much for your correction regarding p-values.  Of course it makes sense to use 5% rather than 50%.  Of course this alteration will change my conclusions and probably my whole presentation.

Also, thank you for sharing ways to make my graphs look nice and stylish.
